### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by NathanFrench** [comment]
WOW... Thank you very much!

**Comment by isaachier** [comment]
Oh don't thank me yet. Still fixing ;).

**Comment by NathanFrench** [comment]
> Still fixing ;).

Just tell me when you're done and I'll merge. Thank you again!

**Comment by isaachier** [comment]
Definitely. No worries really. It's actually been requested as an issue in Hunter package manager: https://github.com/ruslo/hunter/issues/1079. That's what made me look here and decide to invest some time in the CMake build.

**Comment by isaachier** [comment]
OK should be ready now.

**Comment by NathanFrench** [comment]
I don't feel dirty looking at the build file now.

This was top notch work; Thank you very much!

**Comment by isaachier** [comment]
Lol glad to help.

**Pull request merged**
